window.LEAGUE = {"teams": 10, "scoring": "Full PPR", "slot": 5, "rounds": 16, "season": 2026};
window.PLAYERS = [
 {
  "id": "Jahmyr Gibbs",
  "name": "Jahmyr Gibbs",
  "team": "DET",
  "pos": "RB",
  "bye": 6,
  "tier": 1,
  "posRank": 1,
  "adp": 1,
  "boardRank": 1,
  "aav": 57
 },
 {
  "id": "Bijan Robinson",
  "name": "Bijan Robinson",
  "team": "ATL",
  "pos": "RB",
  "bye": 11,
  "tier": 1,
  "posRank": 2,
  "adp": 2,
  "boardRank": 2,
  "aav": 56
 },
 {
  "id": "Puka Nacua",
  "name": "Puka Nacua",
  "team": "LAR",
  "pos": "WR",
  "bye": 11,
  "tier": 1,
  "posRank": 1,
  "adp": 3,
  "boardRank": 3,
  "aav": 56
 },
 {
  "id": "Ja'Marr Chase",
  "name": "Ja'Marr Chase",
  "team": "CIN",
  "pos": "WR",
  "bye": 6,
  "tier": 1,
  "posRank": 2,
  "adp": 4,
  "boardRank": 4,
  "aav": 55
 },
 {
  "id": "Jaxon Smith-Njigba",
  "name": "Jaxon Smith-Njigba",
  "team": "SEA",
  "pos": "WR",
  "bye": 11,
  "tier": 1,
  "posRank": 3,
  "adp": 5,
  "boardRank": 5,
  "aav": 54
 },
 {
  "id": "Christian McCaffrey",
  "name": "Christian McCaffrey",
  "team": "SF",
  "pos": "RB",
  "bye": 8,
  "tier": 2,
  "posRank": 4,
  "adp": 6,
  "boardRank": 6,
  "aav": 53
 },
 {
  "id": "Jonathan Taylor",
  "name": "Jonathan Taylor",
  "team": "IND",
  "pos": "RB",
  "bye": 13,
  "tier": 2,
  "posRank": 7,
  "adp": 7,
  "boardRank": 7,
  "aav": 52
 },
 {
  "id": "Amon-Ra St. Brown",
  "name": "Amon-Ra St. Brown",
  "team": "DET",
  "pos": "WR",
  "bye": 6,
  "tier": 2,
  "posRank": 4,
  "adp": 8,
  "boardRank": 8,
  "aav": 52
 },
 {
  "id": "CeeDee Lamb",
  "name": "CeeDee Lamb",
  "team": "DAL",
  "pos": "WR",
  "bye": 14,
  "tier": 2,
  "posRank": 5,
  "adp": 9,
  "boardRank": 9,
  "aav": 51
 },
 {
  "id": "De'Von Achane",
  "name": "De'Von Achane",
  "team": "MIA",
  "pos": "RB",
  "bye": 6,
  "tier": 3,
  "posRank": 10,
  "adp": 10,
  "boardRank": 10,
  "aav": 50
 },
 {
  "id": "Justin Jefferson",
  "name": "Justin Jefferson",
  "team": "MIN",
  "pos": "WR",
  "bye": 6,
  "tier": 3,
  "posRank": 6,
  "adp": 11,
  "boardRank": 11,
  "aav": 48
 },
 {
  "id": "Jeremiyah Love",
  "name": "Jeremiyah Love",
  "team": "ARI",
  "pos": "RB",
  "bye": 14,
  "tier": 4,
  "posRank": 13,
  "adp": 12,
  "boardRank": 12,
  "aav": 46
 },
 {
  "id": "Drake London",
  "name": "Drake London",
  "team": "ATL",
  "pos": "WR",
  "bye": 11,
  "tier": 3,
  "posRank": 7,
  "adp": 13,
  "boardRank": 13,
  "aav": 45
 },
 {
  "id": "Rashee Rice",
  "name": "Rashee Rice",
  "team": "KC",
  "pos": "WR",
  "bye": 5,
  "tier": 3,
  "posRank": 9,
  "adp": 14,
  "boardRank": 14,
  "aav": 43
 },
 {
  "id": "James Cook III",
  "name": "James Cook III",
  "team": "BUF",
  "pos": "RB",
  "bye": 7,
  "tier": 2,
  "posRank": 5,
  "adp": 15,
  "boardRank": 15,
  "aav": 42
 },
 {
  "id": "Trey McBride",
  "name": "Trey McBride",
  "team": "ARI",
  "pos": "TE",
  "bye": 14,
  "tier": 1,
  "posRank": 1,
  "adp": 16,
  "boardRank": 16,
  "aav": 40
 },
 {
  "id": "Ashton Jeanty",
  "name": "Ashton Jeanty",
  "team": "LV",
  "pos": "RB",
  "bye": 13,
  "tier": 2,
  "posRank": 3,
  "adp": 17,
  "boardRank": 17,
  "aav": 38
 },
 {
  "id": "Omarion Hampton",
  "name": "Omarion Hampton",
  "team": "LAC",
  "pos": "RB",
  "bye": 7,
  "tier": 2,
  "posRank": 6,
  "adp": 18,
  "boardRank": 18,
  "aav": 37
 },
 {
  "id": "Saquon Barkley",
  "name": "Saquon Barkley",
  "team": "PHI",
  "pos": "RB",
  "bye": 10,
  "tier": 3,
  "posRank": 8,
  "adp": 19,
  "boardRank": 19,
  "aav": 36
 },
 {
  "id": "Derrick Henry",
  "name": "Derrick Henry",
  "team": "BAL",
  "pos": "RB",
  "bye": 13,
  "tier": 3,
  "posRank": 11,
  "adp": 20,
  "boardRank": 20,
  "aav": 35
 },
 {
  "id": "Josh Jacobs",
  "name": "Josh Jacobs",
  "team": "GB",
  "pos": "RB",
  "bye": 11,
  "tier": 4,
  "posRank": 15,
  "adp": 21,
  "boardRank": 21,
  "aav": 34
 },
 {
  "id": "Chase Brown",
  "name": "Chase Brown",
  "team": "CIN",
  "pos": "RB",
  "bye": 6,
  "tier": 3,
  "posRank": 12,
  "adp": 22,
  "boardRank": 22,
  "aav": 33
 },
 {
  "id": "Breece Hall",
  "name": "Breece Hall",
  "team": "NYJ",
  "pos": "RB",
  "bye": 13,
  "tier": 5,
  "posRank": 20,
  "adp": 23,
  "boardRank": 23,
  "aav": 32
 },
 {
  "id": "Brock Bowers",
  "name": "Brock Bowers",
  "team": "LV",
  "pos": "TE",
  "bye": 13,
  "tier": 1,
  "posRank": 2,
  "adp": 24,
  "boardRank": 24,
  "aav": 32
 },
 {
  "id": "Nico Collins",
  "name": "Nico Collins",
  "team": "HOU",
  "pos": "WR",
  "bye": 8,
  "tier": 3,
  "posRank": 10,
  "adp": 25,
  "boardRank": 25,
  "aav": 31
 },
 {
  "id": "Garrett Wilson",
  "name": "Garrett Wilson",
  "team": "NYJ",
  "pos": "WR",
  "bye": 13,
  "tier": 4,
  "posRank": 22,
  "adp": 26,
  "boardRank": 26,
  "aav": 30
 },
 {
  "id": "A.J. Brown",
  "name": "A.J. Brown",
  "team": "NE",
  "pos": "WR",
  "bye": 11,
  "tier": 3,
  "posRank": 8,
  "adp": 27,
  "boardRank": 27,
  "aav": 30
 },
 {
  "id": "Chris Olave",
  "name": "Chris Olave",
  "team": "NO",
  "pos": "WR",
  "bye": 8,
  "tier": 4,
  "posRank": 20,
  "adp": 28,
  "boardRank": 28,
  "aav": 29
 },
 {
  "id": "George Pickens",
  "name": "George Pickens",
  "team": "DAL",
  "pos": "WR",
  "bye": 14,
  "tier": 3,
  "posRank": 12,
  "adp": 29,
  "boardRank": 29,
  "aav": 28
 },
 {
  "id": "Kenneth Walker III",
  "name": "Kenneth Walker III",
  "team": "KC",
  "pos": "RB",
  "bye": 5,
  "tier": 3,
  "posRank": 9,
  "adp": 30,
  "boardRank": 30,
  "aav": 27
 },
 {
  "id": "Javonte Williams",
  "name": "Javonte Williams",
  "team": "DAL",
  "pos": "RB",
  "bye": 14,
  "tier": 5,
  "posRank": 21,
  "adp": 31,
  "boardRank": 31,
  "aav": 26
 },
 {
  "id": "Tetairoa McMillan",
  "name": "Tetairoa McMillan",
  "team": "CAR",
  "pos": "WR",
  "bye": 5,
  "tier": 4,
  "posRank": 19,
  "adp": 32,
  "boardRank": 32,
  "aav": 25
 },
 {
  "id": "Zay Flowers",
  "name": "Zay Flowers",
  "team": "BAL",
  "pos": "WR",
  "bye": 13,
  "tier": 4,
  "posRank": 16,
  "adp": 33,
  "boardRank": 33,
  "aav": 24
 },
 {
  "id": "DeVonta Smith",
  "name": "DeVonta Smith",
  "team": "PHI",
  "pos": "WR",
  "bye": 10,
  "tier": 3,
  "posRank": 11,
  "adp": 34,
  "boardRank": 34,
  "aav": 23
 },
 {
  "id": "Emeka Egbuka",
  "name": "Emeka Egbuka",
  "team": "TB",
  "pos": "WR",
  "bye": 10,
  "tier": 4,
  "posRank": 14,
  "adp": 35,
  "boardRank": 35,
  "aav": 22
 },
 {
  "id": "Josh Allen",
  "name": "Josh Allen",
  "team": "BUF",
  "pos": "QB",
  "bye": 7,
  "tier": 1,
  "posRank": 1,
  "adp": 36,
  "boardRank": 36,
  "aav": 22
 },
 {
  "id": "Kyren Williams",
  "name": "Kyren Williams",
  "team": "LAR",
  "pos": "RB",
  "bye": 11,
  "tier": 4,
  "posRank": 14,
  "adp": 37,
  "boardRank": 37,
  "aav": 22
 },
 {
  "id": "Travis Etienne Jr.",
  "name": "Travis Etienne Jr.",
  "team": "NO",
  "pos": "RB",
  "bye": 8,
  "tier": 5,
  "posRank": 22,
  "adp": 38,
  "boardRank": 38,
  "aav": 21
 },
 {
  "id": "Cam Skattebo",
  "name": "Cam Skattebo",
  "team": "NYG",
  "pos": "RB",
  "bye": 8,
  "tier": 4,
  "posRank": 16,
  "adp": 39,
  "boardRank": 39,
  "aav": 21
 },
 {
  "id": "Quinshon Judkins",
  "name": "Quinshon Judkins",
  "team": "CLE",
  "pos": "RB",
  "bye": 11,
  "tier": 4,
  "posRank": 17,
  "adp": 40,
  "boardRank": 40,
  "aav": 20
 },
 {
  "id": "Bucky Irving",
  "name": "Bucky Irving",
  "team": "TB",
  "pos": "RB",
  "bye": 10,
  "tier": 5,
  "posRank": 23,
  "adp": 41,
  "boardRank": 41,
  "aav": 19
 },
 {
  "id": "Malik Nabers",
  "name": "Malik Nabers",
  "team": "NYG",
  "pos": "WR",
  "bye": 8,
  "tier": 5,
  "posRank": 23,
  "adp": 42,
  "boardRank": 42,
  "aav": 19
 },
 {
  "id": "Davante Adams",
  "name": "Davante Adams",
  "team": "LAR",
  "pos": "WR",
  "bye": 11,
  "tier": 4,
  "posRank": 17,
  "adp": 43,
  "boardRank": 43,
  "aav": 18
 },
 {
  "id": "Ladd McConkey",
  "name": "Ladd McConkey",
  "team": "LAC",
  "pos": "WR",
  "bye": 7,
  "tier": 4,
  "posRank": 15,
  "adp": 44,
  "boardRank": 44,
  "aav": 17
 },
 {
  "id": "Terry McLaurin",
  "name": "Terry McLaurin",
  "team": "WAS",
  "pos": "WR",
  "bye": 7,
  "tier": 4,
  "posRank": 21,
  "adp": 45,
  "boardRank": 45,
  "aav": 17
 },
 {
  "id": "Tee Higgins",
  "name": "Tee Higgins",
  "team": "CIN",
  "pos": "WR",
  "bye": 6,
  "tier": 4,
  "posRank": 13,
  "adp": 46,
  "boardRank": 46,
  "aav": 15
 },
 {
  "id": "Jaylen Waddle",
  "name": "Jaylen Waddle",
  "team": "DEN",
  "pos": "WR",
  "bye": 10,
  "tier": 5,
  "posRank": 25,
  "adp": 47,
  "boardRank": 47,
  "aav": 15
 },
 {
  "id": "Jameson Williams",
  "name": "Jameson Williams",
  "team": "DET",
  "pos": "WR",
  "bye": 6,
  "tier": 5,
  "posRank": 27,
  "adp": 48,
  "boardRank": 48,
  "aav": 14
 },
 {
  "id": "Colston Loveland",
  "name": "Colston Loveland",
  "team": "CHI",
  "pos": "TE",
  "bye": 10,
  "tier": 1,
  "posRank": 3,
  "adp": 49,
  "boardRank": 49,
  "aav": 13
 },
 {
  "id": "Tyler Warren",
  "name": "Tyler Warren",
  "team": "IND",
  "pos": "TE",
  "bye": 13,
  "tier": 2,
  "posRank": 4,
  "adp": 50,
  "boardRank": 50,
  "aav": 13
 },
 {
  "id": "Carnell Tate",
  "name": "Carnell Tate",
  "team": "TEN",
  "pos": "WR",
  "bye": 9,
  "tier": 7,
  "posRank": 30,
  "adp": 51,
  "boardRank": 51,
  "aav": 12
 },
 {
  "id": "Rome Odunze",
  "name": "Rome Odunze",
  "team": "CHI",
  "pos": "WR",
  "bye": 10,
  "tier": 5,
  "posRank": 28,
  "adp": 52,
  "boardRank": 52,
  "aav": 11
 },
 {
  "id": "Luther Burden III",
  "name": "Luther Burden III",
  "team": "CHI",
  "pos": "WR",
  "bye": 10,
  "tier": 5,
  "posRank": 24,
  "adp": 53,
  "boardRank": 53,
  "aav": 11
 },
 {
  "id": "DJ Moore",
  "name": "DJ Moore",
  "team": "BUF",
  "pos": "WR",
  "bye": 7,
  "tier": 7,
  "posRank": 31,
  "adp": 54,
  "boardRank": 54,
  "aav": 10
 },
 {
  "id": "Jayden Daniels",
  "name": "Jayden Daniels",
  "team": "WAS",
  "pos": "QB",
  "bye": 7,
  "tier": 1,
  "posRank": 2,
  "adp": 55,
  "boardRank": 55,
  "aav": 10
 },
 {
  "id": "Lamar Jackson",
  "name": "Lamar Jackson",
  "team": "BAL",
  "pos": "QB",
  "bye": 13,
  "tier": 1,
  "posRank": 3,
  "adp": 56,
  "boardRank": 56,
  "aav": 10
 },
 {
  "id": "Drake Maye",
  "name": "Drake Maye",
  "team": "NE",
  "pos": "QB",
  "bye": 11,
  "tier": 1,
  "posRank": 4,
  "adp": 57,
  "boardRank": 57,
  "aav": 10
 },
 {
  "id": "Jalen Hurts",
  "name": "Jalen Hurts",
  "team": "PHI",
  "pos": "QB",
  "bye": 10,
  "tier": 2,
  "posRank": 5,
  "adp": 58,
  "boardRank": 58,
  "aav": 9
 },
 {
  "id": "TreVeyon Henderson",
  "name": "TreVeyon Henderson",
  "team": "NE",
  "pos": "RB",
  "bye": 11,
  "tier": 4,
  "posRank": 18,
  "adp": 59,
  "boardRank": 59,
  "aav": 9
 },
 {
  "id": "Bhayshul Tuten",
  "name": "Bhayshul Tuten",
  "team": "JAC",
  "pos": "RB",
  "bye": 7,
  "tier": 4,
  "posRank": 19,
  "adp": 60,
  "boardRank": 60,
  "aav": 9
 },
 {
  "id": "Jadarian Price",
  "name": "Jadarian Price",
  "team": "SEA",
  "pos": "RB",
  "bye": 11,
  "tier": 5,
  "posRank": 24,
  "adp": 61,
  "boardRank": 61,
  "aav": 8
 },
 {
  "id": "D'Andre Swift",
  "name": "D'Andre Swift",
  "team": "CHI",
  "pos": "RB",
  "bye": 10,
  "tier": 5,
  "posRank": 25,
  "adp": 62,
  "boardRank": 62,
  "aav": 8
 },
 {
  "id": "David Montgomery",
  "name": "David Montgomery",
  "team": "HOU",
  "pos": "RB",
  "bye": 8,
  "tier": 5,
  "posRank": 26,
  "adp": 63,
  "boardRank": 63,
  "aav": 8
 },
 {
  "id": "Tony Pollard",
  "name": "Tony Pollard",
  "team": "TEN",
  "pos": "RB",
  "bye": 9,
  "tier": 5,
  "posRank": 27,
  "adp": 64,
  "boardRank": 64,
  "aav": 7
 },
 {
  "id": "Marvin Harrison Jr.",
  "name": "Marvin Harrison Jr.",
  "team": "ARI",
  "pos": "WR",
  "bye": 14,
  "tier": 5,
  "posRank": 26,
  "adp": 65,
  "boardRank": 65,
  "aav": 7
 },
 {
  "id": "Courtland Sutton",
  "name": "Courtland Sutton",
  "team": "DEN",
  "pos": "WR",
  "bye": 10,
  "tier": 7,
  "posRank": 32,
  "adp": 66,
  "boardRank": 66,
  "aav": 7
 },
 {
  "id": "Michael Pittman Jr.",
  "name": "Michael Pittman Jr.",
  "team": "PIT",
  "pos": "WR",
  "bye": 9,
  "tier": 7,
  "posRank": 33,
  "adp": 67,
  "boardRank": 67,
  "aav": 7
 },
 {
  "id": "DK Metcalf",
  "name": "DK Metcalf",
  "team": "PIT",
  "pos": "WR",
  "bye": 9,
  "tier": 7,
  "posRank": 34,
  "adp": 68,
  "boardRank": 68,
  "aav": 6
 },
 {
  "id": "Alec Pierce",
  "name": "Alec Pierce",
  "team": "IND",
  "pos": "WR",
  "bye": 13,
  "tier": 7,
  "posRank": 35,
  "adp": 69,
  "boardRank": 69,
  "aav": 6
 },
 {
  "id": "Jordyn Tyson",
  "name": "Jordyn Tyson",
  "team": "NO",
  "pos": "WR",
  "bye": 8,
  "tier": 7,
  "posRank": 36,
  "adp": 70,
  "boardRank": 70,
  "aav": 6
 },
 {
  "id": "Kyle Pitts Sr.",
  "name": "Kyle Pitts Sr.",
  "team": "ATL",
  "pos": "TE",
  "bye": 11,
  "tier": 2,
  "posRank": 5,
  "adp": 71,
  "boardRank": 71,
  "aav": 6
 },
 {
  "id": "Harold Fannin Jr.",
  "name": "Harold Fannin Jr.",
  "team": "CLE",
  "pos": "TE",
  "bye": 11,
  "tier": 2,
  "posRank": 6,
  "adp": 72,
  "boardRank": 72,
  "aav": 6
 },
 {
  "id": "Sam LaPorta",
  "name": "Sam LaPorta",
  "team": "DET",
  "pos": "TE",
  "bye": 6,
  "tier": 3,
  "posRank": 7,
  "adp": 73,
  "boardRank": 73,
  "aav": 6
 },
 {
  "id": "Joe Burrow",
  "name": "Joe Burrow",
  "team": "CIN",
  "pos": "QB",
  "bye": 6,
  "tier": 2,
  "posRank": 6,
  "adp": 74,
  "boardRank": 74,
  "aav": 5
 },
 {
  "id": "Jaxson Dart",
  "name": "Jaxson Dart",
  "team": "NYG",
  "pos": "QB",
  "bye": 8,
  "tier": 2,
  "posRank": 7,
  "adp": 75,
  "boardRank": 75,
  "aav": 5
 },
 {
  "id": "Parker Washington",
  "name": "Parker Washington",
  "team": "JAC",
  "pos": "WR",
  "bye": 7,
  "tier": 7,
  "posRank": 37,
  "adp": 76,
  "boardRank": 76,
  "aav": 5
 },
 {
  "id": "Christian Watson",
  "name": "Christian Watson",
  "team": "GB",
  "pos": "WR",
  "bye": 11,
  "tier": 6,
  "posRank": 29,
  "adp": 77,
  "boardRank": 77,
  "aav": 5
 },
 {
  "id": "Matthew Golden",
  "name": "Matthew Golden",
  "team": "GB",
  "pos": "WR",
  "bye": 11,
  "tier": 7,
  "posRank": 38,
  "adp": 78,
  "boardRank": 78,
  "aav": 4
 },
 {
  "id": "Mike Evans",
  "name": "Mike Evans",
  "team": "SF",
  "pos": "WR",
  "bye": 8,
  "tier": 4,
  "posRank": 18,
  "adp": 79,
  "boardRank": 79,
  "aav": 4
 },
 {
  "id": "Brian Thomas Jr.",
  "name": "Brian Thomas Jr.",
  "team": "JAC",
  "pos": "WR",
  "bye": 7,
  "tier": 7,
  "posRank": 39,
  "adp": 80,
  "boardRank": 80,
  "aav": 4
 },
 {
  "id": "Jakobi Meyers",
  "name": "Jakobi Meyers",
  "team": "JAC",
  "pos": "WR",
  "bye": 7,
  "tier": 7,
  "posRank": 40,
  "adp": 81,
  "boardRank": 81,
  "aav": 4
 },
 {
  "id": "Trevor Lawrence",
  "name": "Trevor Lawrence",
  "team": "JAC",
  "pos": "QB",
  "bye": 7,
  "tier": 2,
  "posRank": 8,
  "adp": 82,
  "boardRank": 82,
  "aav": 4
 },
 {
  "id": "Dak Prescott",
  "name": "Dak Prescott",
  "team": "DAL",
  "pos": "QB",
  "bye": 14,
  "tier": 3,
  "posRank": 9,
  "adp": 83,
  "boardRank": 83,
  "aav": 4
 },
 {
  "id": "Bo Nix",
  "name": "Bo Nix",
  "team": "DEN",
  "pos": "QB",
  "bye": 10,
  "tier": 3,
  "posRank": 10,
  "adp": 84,
  "boardRank": 84,
  "aav": 4
 },
 {
  "id": "Brock Purdy",
  "name": "Brock Purdy",
  "team": "SF",
  "pos": "QB",
  "bye": 8,
  "tier": 3,
  "posRank": 11,
  "adp": 85,
  "boardRank": 85,
  "aav": 4
 },
 {
  "id": "Matthew Stafford",
  "name": "Matthew Stafford",
  "team": "LAR",
  "pos": "QB",
  "bye": 11,
  "tier": 3,
  "posRank": 12,
  "adp": 86,
  "boardRank": 86,
  "aav": 4
 },
 {
  "id": "Caleb Williams",
  "name": "Caleb Williams",
  "team": "CHI",
  "pos": "QB",
  "bye": 10,
  "tier": 4,
  "posRank": 13,
  "adp": 87,
  "boardRank": 87,
  "aav": 3
 },
 {
  "id": "Wan'Dale Robinson",
  "name": "Wan'Dale Robinson",
  "team": "TEN",
  "pos": "WR",
  "bye": 9,
  "tier": 7,
  "posRank": 41,
  "adp": 88,
  "boardRank": 88,
  "aav": 3
 },
 {
  "id": "Makai Lemon",
  "name": "Makai Lemon",
  "team": "PHI",
  "pos": "WR",
  "bye": 10,
  "tier": 7,
  "posRank": 42,
  "adp": 89,
  "boardRank": 89,
  "aav": 3
 },
 {
  "id": "Michael Wilson",
  "name": "Michael Wilson",
  "team": "ARI",
  "pos": "WR",
  "bye": 14,
  "tier": 7,
  "posRank": 43,
  "adp": 90,
  "boardRank": 90,
  "aav": 3
 },
 {
  "id": "Ricky Pearsall",
  "name": "Ricky Pearsall",
  "team": "SF",
  "pos": "WR",
  "bye": 8,
  "tier": 7,
  "posRank": 44,
  "adp": 91,
  "boardRank": 91,
  "aav": 3
 },
 {
  "id": "Jordan Addison",
  "name": "Jordan Addison",
  "team": "MIN",
  "pos": "WR",
  "bye": 6,
  "tier": 7,
  "posRank": 45,
  "adp": 92,
  "boardRank": 92,
  "aav": 3
 },
 {
  "id": "Justin Herbert",
  "name": "Justin Herbert",
  "team": "LAC",
  "pos": "QB",
  "bye": 7,
  "tier": 4,
  "posRank": 14,
  "adp": 93,
  "boardRank": 93,
  "aav": 3
 },
 {
  "id": "Patrick Mahomes",
  "name": "Patrick Mahomes",
  "team": "KC",
  "pos": "QB",
  "bye": 5,
  "tier": 4,
  "posRank": 15,
  "adp": 94,
  "boardRank": 94,
  "aav": 3
 },
 {
  "id": "Jaylen Warren",
  "name": "Jaylen Warren",
  "team": "PIT",
  "pos": "RB",
  "bye": 9,
  "tier": 5,
  "posRank": 28,
  "adp": 95,
  "boardRank": 95,
  "aav": 3
 },
 {
  "id": "Rhamondre Stevenson",
  "name": "Rhamondre Stevenson",
  "team": "NE",
  "pos": "RB",
  "bye": 11,
  "tier": 5,
  "posRank": 29,
  "adp": 96,
  "boardRank": 96,
  "aav": 2
 },
 {
  "id": "Rico Dowdle",
  "name": "Rico Dowdle",
  "team": "PIT",
  "pos": "RB",
  "bye": 9,
  "tier": 5,
  "posRank": 30,
  "adp": 97,
  "boardRank": 97,
  "aav": 2
 },
 {
  "id": "Chuba Hubbard",
  "name": "Chuba Hubbard",
  "team": "CAR",
  "pos": "RB",
  "bye": 5,
  "tier": 5,
  "posRank": 31,
  "adp": 98,
  "boardRank": 98,
  "aav": 2
 },
 {
  "id": "Aaron Jones Sr.",
  "name": "Aaron Jones Sr.",
  "team": "MIN",
  "pos": "RB",
  "bye": 6,
  "tier": 5,
  "posRank": 32,
  "adp": 99,
  "boardRank": 99,
  "aav": 2
 },
 {
  "id": "Kenny Gainwell",
  "name": "Kenny Gainwell",
  "team": "TB",
  "pos": "RB",
  "bye": 10,
  "tier": 5,
  "posRank": 33,
  "adp": 100,
  "boardRank": 100,
  "aav": 2
 },
 {
  "id": "George Kittle",
  "name": "George Kittle",
  "team": "SF",
  "pos": "TE",
  "bye": 8,
  "tier": 3,
  "posRank": 8,
  "adp": 101,
  "boardRank": 101,
  "aav": 2
 },
 {
  "id": "Dallas Goedert",
  "name": "Dallas Goedert",
  "team": "PHI",
  "pos": "TE",
  "bye": 10,
  "tier": 3,
  "posRank": 9,
  "adp": 102,
  "boardRank": 102,
  "aav": 2
 },
 {
  "id": "Travis Kelce",
  "name": "Travis Kelce",
  "team": "KC",
  "pos": "TE",
  "bye": 5,
  "tier": 3,
  "posRank": 10,
  "adp": 103,
  "boardRank": 103,
  "aav": 2
 },
 {
  "id": "Jake Ferguson",
  "name": "Jake Ferguson",
  "team": "DAL",
  "pos": "TE",
  "bye": 14,
  "tier": 4,
  "posRank": 11,
  "adp": 104,
  "boardRank": 104,
  "aav": 2
 },
 {
  "id": "Rachaad White",
  "name": "Rachaad White",
  "team": "WAS",
  "pos": "RB",
  "bye": 7,
  "tier": 5,
  "posRank": 34,
  "adp": 105,
  "boardRank": 105,
  "aav": 2
 },
 {
  "id": "J.K. Dobbins",
  "name": "J.K. Dobbins",
  "team": "DEN",
  "pos": "RB",
  "bye": 10,
  "tier": 5,
  "posRank": 35,
  "adp": 106,
  "boardRank": 106,
  "aav": 2
 },
 {
  "id": "RJ Harvey",
  "name": "RJ Harvey",
  "team": "DEN",
  "pos": "RB",
  "bye": 10,
  "tier": 5,
  "posRank": 36,
  "adp": 107,
  "boardRank": 107,
  "aav": 2
 },
 {
  "id": "Kyle Monangai",
  "name": "Kyle Monangai",
  "team": "CHI",
  "pos": "RB",
  "bye": 10,
  "tier": 6,
  "posRank": 37,
  "adp": 108,
  "boardRank": 108,
  "aav": 2
 },
 {
  "id": "Mark Andrews",
  "name": "Mark Andrews",
  "team": "BAL",
  "pos": "TE",
  "bye": 13,
  "tier": 4,
  "posRank": 12,
  "adp": 109,
  "boardRank": 109,
  "aav": 2
 },
 {
  "id": "Tucker Kraft",
  "name": "Tucker Kraft",
  "team": "GB",
  "pos": "TE",
  "bye": 11,
  "tier": 4,
  "posRank": 13,
  "adp": 110,
  "boardRank": 110,
  "aav": 2
 },
 {
  "id": "T.J. Hockenson",
  "name": "T.J. Hockenson",
  "team": "MIN",
  "pos": "TE",
  "bye": 6,
  "tier": 4,
  "posRank": 14,
  "adp": 111,
  "boardRank": 111,
  "aav": 2
 },
 {
  "id": "Khalil Shakir",
  "name": "Khalil Shakir",
  "team": "BUF",
  "pos": "WR",
  "bye": 7,
  "tier": 8,
  "posRank": 46,
  "adp": 112,
  "boardRank": 112,
  "aav": 2
 },
 {
  "id": "Jayden Reed",
  "name": "Jayden Reed",
  "team": "GB",
  "pos": "WR",
  "bye": 11,
  "tier": 8,
  "posRank": 47,
  "adp": 113,
  "boardRank": 113,
  "aav": 2
 },
 {
  "id": "Josh Downs",
  "name": "Josh Downs",
  "team": "IND",
  "pos": "WR",
  "bye": 13,
  "tier": 8,
  "posRank": 48,
  "adp": 114,
  "boardRank": 114,
  "aav": 2
 },
 {
  "id": "Jonathon Brooks",
  "name": "Jonathon Brooks",
  "team": "CAR",
  "pos": "RB",
  "bye": 5,
  "tier": 6,
  "posRank": 38,
  "adp": 115,
  "boardRank": 115,
  "aav": 2
 },
 {
  "id": "Kenyon Sadiq",
  "name": "Kenyon Sadiq",
  "team": "NYJ",
  "pos": "TE",
  "bye": 13,
  "tier": 4,
  "posRank": 15,
  "adp": 116,
  "boardRank": 116,
  "aav": 2
 },
 {
  "id": "Isaiah Likely",
  "name": "Isaiah Likely",
  "team": "NYG",
  "pos": "TE",
  "bye": 8,
  "tier": 4,
  "posRank": 16,
  "adp": 117,
  "boardRank": 117,
  "aav": 2
 },
 {
  "id": "Dalton Kincaid",
  "name": "Dalton Kincaid",
  "team": "BUF",
  "pos": "TE",
  "bye": 7,
  "tier": 5,
  "posRank": 17,
  "adp": 118,
  "boardRank": 118,
  "aav": 2
 },
 {
  "id": "Hunter Henry",
  "name": "Hunter Henry",
  "team": "NE",
  "pos": "TE",
  "bye": 11,
  "tier": 5,
  "posRank": 18,
  "adp": 119,
  "boardRank": 119,
  "aav": 2
 },
 {
  "id": "Jacory Croskey-Merritt",
  "name": "Jacory Croskey-Merritt",
  "team": "WAS",
  "pos": "RB",
  "bye": 7,
  "tier": 6,
  "posRank": 39,
  "adp": 120,
  "boardRank": 120,
  "aav": 2
 },
 {
  "id": "Blake Corum",
  "name": "Blake Corum",
  "team": "LAR",
  "pos": "RB",
  "bye": 11,
  "tier": 6,
  "posRank": 40,
  "adp": 121,
  "boardRank": 121,
  "aav": 1
 },
 {
  "id": "Woody Marks",
  "name": "Woody Marks",
  "team": "HOU",
  "pos": "RB",
  "bye": 8,
  "tier": 6,
  "posRank": 41,
  "adp": 122,
  "boardRank": 122,
  "aav": 1
 },
 {
  "id": "Jordan Mason",
  "name": "Jordan Mason",
  "team": "MIN",
  "pos": "RB",
  "bye": 6,
  "tier": 6,
  "posRank": 42,
  "adp": 123,
  "boardRank": 123,
  "aav": 1
 },
 {
  "id": "KC Concepcion",
  "name": "KC Concepcion",
  "team": "CLE",
  "pos": "WR",
  "bye": 11,
  "tier": 8,
  "posRank": 49,
  "adp": 124,
  "boardRank": 124,
  "aav": 1
 },
 {
  "id": "Chris Godwin Jr.",
  "name": "Chris Godwin Jr.",
  "team": "TB",
  "pos": "WR",
  "bye": 10,
  "tier": 8,
  "posRank": 50,
  "adp": 125,
  "boardRank": 125,
  "aav": 1
 },
 {
  "id": "Xavier Worthy",
  "name": "Xavier Worthy",
  "team": "KC",
  "pos": "WR",
  "bye": 5,
  "tier": 8,
  "posRank": 51,
  "adp": 126,
  "boardRank": 126,
  "aav": 1
 },
 {
  "id": "Romeo Doubs",
  "name": "Romeo Doubs",
  "team": "NE",
  "pos": "WR",
  "bye": 11,
  "tier": 8,
  "posRank": 52,
  "adp": 127,
  "boardRank": 127,
  "aav": 1
 },
 {
  "id": "Quentin Johnston",
  "name": "Quentin Johnston",
  "team": "LAC",
  "pos": "WR",
  "bye": 7,
  "tier": 8,
  "posRank": 53,
  "adp": 128,
  "boardRank": 128,
  "aav": 1
 },
 {
  "id": "Jayden Higgins",
  "name": "Jayden Higgins",
  "team": "HOU",
  "pos": "WR",
  "bye": 8,
  "tier": 8,
  "posRank": 54,
  "adp": 129,
  "boardRank": 129,
  "aav": 1
 },
 {
  "id": "Jerry Jeudy",
  "name": "Jerry Jeudy",
  "team": "CLE",
  "pos": "WR",
  "bye": 11,
  "tier": 8,
  "posRank": 55,
  "adp": 130,
  "boardRank": 130,
  "aav": 1
 },
 {
  "id": "Jalen Coker",
  "name": "Jalen Coker",
  "team": "CAR",
  "pos": "WR",
  "bye": 5,
  "tier": 8,
  "posRank": 56,
  "adp": 131,
  "boardRank": 131,
  "aav": 1
 },
 {
  "id": "Rashid Shaheed",
  "name": "Rashid Shaheed",
  "team": "SEA",
  "pos": "WR",
  "bye": 11,
  "tier": 8,
  "posRank": 57,
  "adp": 132,
  "boardRank": 132,
  "aav": 1
 },
 {
  "id": "Kyler Murray",
  "name": "Kyler Murray",
  "team": "MIN",
  "pos": "QB",
  "bye": 6,
  "tier": 4,
  "posRank": 16,
  "adp": 133,
  "boardRank": 133,
  "aav": 1
 },
 {
  "id": "Tyler Shough",
  "name": "Tyler Shough",
  "team": "NO",
  "pos": "QB",
  "bye": 8,
  "tier": 5,
  "posRank": 17,
  "adp": 134,
  "boardRank": 134,
  "aav": 1
 },
 {
  "id": "Daniel Jones",
  "name": "Daniel Jones",
  "team": "IND",
  "pos": "QB",
  "bye": 13,
  "tier": 5,
  "posRank": 18,
  "adp": 135,
  "boardRank": 135,
  "aav": 1
 },
 {
  "id": "Jared Goff",
  "name": "Jared Goff",
  "team": "DET",
  "pos": "QB",
  "bye": 6,
  "tier": 5,
  "posRank": 19,
  "adp": 136,
  "boardRank": 136,
  "aav": 1
 },
 {
  "id": "Zach Charbonnet",
  "name": "Zach Charbonnet",
  "team": "SEA",
  "pos": "RB",
  "bye": 11,
  "tier": 6,
  "posRank": 43,
  "adp": 137,
  "boardRank": 137,
  "aav": 1
 },
 {
  "id": "Alvin Kamara",
  "name": "Alvin Kamara",
  "team": "NO",
  "pos": "RB",
  "bye": 8,
  "tier": 6,
  "posRank": 44,
  "adp": 138,
  "boardRank": 138,
  "aav": 1
 },
 {
  "id": "Isiah Pacheco",
  "name": "Isiah Pacheco",
  "team": "DET",
  "pos": "RB",
  "bye": 6,
  "tier": 6,
  "posRank": 45,
  "adp": 139,
  "boardRank": 139,
  "aav": 1
 },
 {
  "id": "Chris Rodriguez Jr.",
  "name": "Chris Rodriguez Jr.",
  "team": "JAC",
  "pos": "RB",
  "bye": 7,
  "tier": 6,
  "posRank": 46,
  "adp": 140,
  "boardRank": 140,
  "aav": 1
 },
 {
  "id": "Braelon Allen",
  "name": "Braelon Allen",
  "team": "NYJ",
  "pos": "RB",
  "bye": 13,
  "tier": 6,
  "posRank": 47,
  "adp": 141,
  "boardRank": 141,
  "aav": 1
 },
 {
  "id": "Tank Bigsby",
  "name": "Tank Bigsby",
  "team": "PHI",
  "pos": "RB",
  "bye": 10,
  "tier": 6,
  "posRank": 48,
  "adp": 142,
  "boardRank": 142,
  "aav": 1
 },
 {
  "id": "Jalen McMillan",
  "name": "Jalen McMillan",
  "team": "TB",
  "pos": "WR",
  "bye": 10,
  "tier": 8,
  "posRank": 58,
  "adp": 143,
  "boardRank": 143,
  "aav": 1
 },
 {
  "id": "Calvin Ridley",
  "name": "Calvin Ridley",
  "team": "TEN",
  "pos": "WR",
  "bye": 9,
  "tier": 8,
  "posRank": 59,
  "adp": 144,
  "boardRank": 144,
  "aav": 1
 },
 {
  "id": "Denzel Boston",
  "name": "Denzel Boston",
  "team": "CLE",
  "pos": "WR",
  "bye": 11,
  "tier": 8,
  "posRank": 60,
  "adp": 145,
  "boardRank": 145,
  "aav": 1
 },
 {
  "id": "Travis Hunter",
  "name": "Travis Hunter",
  "team": "JAC",
  "pos": "WR",
  "bye": 7,
  "tier": 8,
  "posRank": 61,
  "adp": 146,
  "boardRank": 146,
  "aav": 1
 },
 {
  "id": "Germie Bernard",
  "name": "Germie Bernard",
  "team": "PIT",
  "pos": "WR",
  "bye": 9,
  "tier": 8,
  "posRank": 62,
  "adp": 147,
  "boardRank": 147,
  "aav": 1
 },
 {
  "id": "Antonio Williams",
  "name": "Antonio Williams",
  "team": "WAS",
  "pos": "WR",
  "bye": 7,
  "tier": 8,
  "posRank": 63,
  "adp": 148,
  "boardRank": 148,
  "aav": 1
 },
 {
  "id": "Baker Mayfield",
  "name": "Baker Mayfield",
  "team": "TB",
  "pos": "QB",
  "bye": 10,
  "tier": 5,
  "posRank": 20,
  "adp": 149,
  "boardRank": 149,
  "aav": 1
 },
 {
  "id": "Malik Willis",
  "name": "Malik Willis",
  "team": "MIA",
  "pos": "QB",
  "bye": 6,
  "tier": 5,
  "posRank": 21,
  "adp": 150,
  "boardRank": 150,
  "aav": 1
 },
 {
  "id": "Adonai Mitchell",
  "name": "Adonai Mitchell",
  "team": "NYJ",
  "pos": "WR",
  "bye": 13,
  "tier": 8,
  "posRank": 64,
  "adp": 151,
  "boardRank": 151,
  "aav": 1
 },
 {
  "id": "Omar Cooper Jr.",
  "name": "Omar Cooper Jr.",
  "team": "NYJ",
  "pos": "WR",
  "bye": 13,
  "tier": 8,
  "posRank": 65,
  "adp": 152,
  "boardRank": 152,
  "aav": 1
 },
 {
  "id": "Tre Tucker",
  "name": "Tre Tucker",
  "team": "LV",
  "pos": "WR",
  "bye": 13,
  "tier": 8,
  "posRank": 66,
  "adp": 153,
  "boardRank": 153,
  "aav": 1
 },
 {
  "id": "Mike Washington Jr.",
  "name": "Mike Washington Jr.",
  "team": "LV",
  "pos": "RB",
  "bye": 13,
  "tier": 6,
  "posRank": 49,
  "adp": 154,
  "boardRank": 154,
  "aav": 1
 },
 {
  "id": "Ray Davis",
  "name": "Ray Davis",
  "team": "BUF",
  "pos": "RB",
  "bye": 7,
  "tier": 6,
  "posRank": 50,
  "adp": 155,
  "boardRank": 155,
  "aav": 1
 },
 {
  "id": "Tyrone Tracy Jr.",
  "name": "Tyrone Tracy Jr.",
  "team": "NYG",
  "pos": "RB",
  "bye": 8,
  "tier": 7,
  "posRank": 51,
  "adp": 156,
  "boardRank": 156,
  "aav": 1
 },
 {
  "id": "Brian Robinson Jr.",
  "name": "Brian Robinson Jr.",
  "team": "ATL",
  "pos": "RB",
  "bye": 11,
  "tier": 7,
  "posRank": 52,
  "adp": 157,
  "boardRank": 157,
  "aav": 1
 },
 {
  "id": "Tyjae Spears",
  "name": "Tyjae Spears",
  "team": "TEN",
  "pos": "RB",
  "bye": 9,
  "tier": 7,
  "posRank": 53,
  "adp": 158,
  "boardRank": 158,
  "aav": 1
 },
 {
  "id": "Terrance Ferguson",
  "name": "Terrance Ferguson",
  "team": "LAR",
  "pos": "TE",
  "bye": 11,
  "tier": 5,
  "posRank": 19,
  "adp": 159,
  "boardRank": 159,
  "aav": 1
 },
 {
  "id": "Juwan Johnson",
  "name": "Juwan Johnson",
  "team": "NO",
  "pos": "TE",
  "bye": 8,
  "tier": 5,
  "posRank": 20,
  "adp": 160,
  "boardRank": 160,
  "aav": 1
 },
 {
  "id": "Jalen Nailor",
  "name": "Jalen Nailor",
  "team": "LV",
  "pos": "WR",
  "bye": 13,
  "tier": 8,
  "posRank": 67,
  "adp": 161,
  "boardRank": 161,
  "aav": 0
 },
 {
  "id": "Rashod Bateman",
  "name": "Rashod Bateman",
  "team": "BAL",
  "pos": "WR",
  "bye": 13,
  "tier": 8,
  "posRank": 68,
  "adp": 162,
  "boardRank": 162,
  "aav": 0
 },
 {
  "id": "Jauan Jennings",
  "name": "Jauan Jennings",
  "team": "MIN",
  "pos": "WR",
  "bye": 6,
  "tier": 8,
  "posRank": 69,
  "adp": 163,
  "boardRank": 163,
  "aav": 0
 },
 {
  "id": "Jaylin Noel",
  "name": "Jaylin Noel",
  "team": "HOU",
  "pos": "WR",
  "bye": 8,
  "tier": 8,
  "posRank": 70,
  "adp": 164,
  "boardRank": 164,
  "aav": 0
 },
 {
  "id": "Darnell Mooney",
  "name": "Darnell Mooney",
  "team": "NYG",
  "pos": "WR",
  "bye": 8,
  "tier": 8,
  "posRank": 71,
  "adp": 165,
  "boardRank": 165,
  "aav": 0
 },
 {
  "id": "Tyler Allgeier",
  "name": "Tyler Allgeier",
  "team": "ARI",
  "pos": "RB",
  "bye": 14,
  "tier": 7,
  "posRank": 54,
  "adp": 166,
  "boardRank": 166,
  "aav": 0
 },
 {
  "id": "James Conner",
  "name": "James Conner",
  "team": "ARI",
  "pos": "RB",
  "bye": 14,
  "tier": 7,
  "posRank": 55,
  "adp": 167,
  "boardRank": 167,
  "aav": 0
 },
 {
  "id": "Keaton Mitchell",
  "name": "Keaton Mitchell",
  "team": "LAC",
  "pos": "RB",
  "bye": 7,
  "tier": 7,
  "posRank": 56,
  "adp": 168,
  "boardRank": 168,
  "aav": 0
 },
 {
  "id": "Broncos",
  "name": "Broncos",
  "team": null,
  "pos": "DST",
  "bye": 10,
  "tier": 1,
  "posRank": 1,
  "adp": 169,
  "boardRank": 169,
  "aav": 1
 },
 {
  "id": "Texans",
  "name": "Texans",
  "team": null,
  "pos": "DST",
  "bye": 8,
  "tier": 1,
  "posRank": 2,
  "adp": 170,
  "boardRank": 170,
  "aav": 1
 },
 {
  "id": "Steelers",
  "name": "Steelers",
  "team": null,
  "pos": "DST",
  "bye": 9,
  "tier": 1,
  "posRank": 3,
  "adp": 171,
  "boardRank": 171,
  "aav": 1
 },
 {
  "id": "Seahawks",
  "name": "Seahawks",
  "team": null,
  "pos": "DST",
  "bye": 11,
  "tier": 2,
  "posRank": 4,
  "adp": 172,
  "boardRank": 172,
  "aav": 1
 },
 {
  "id": "Rams",
  "name": "Rams",
  "team": null,
  "pos": "DST",
  "bye": 11,
  "tier": 2,
  "posRank": 5,
  "adp": 173,
  "boardRank": 173,
  "aav": 1
 },
 {
  "id": "Ravens",
  "name": "Ravens",
  "team": null,
  "pos": "DST",
  "bye": 13,
  "tier": 2,
  "posRank": 6,
  "adp": 174,
  "boardRank": 174,
  "aav": 1
 },
 {
  "id": "Eagles",
  "name": "Eagles",
  "team": null,
  "pos": "DST",
  "bye": 10,
  "tier": 2,
  "posRank": 7,
  "adp": 175,
  "boardRank": 175,
  "aav": 1
 },
 {
  "id": "Browns",
  "name": "Browns",
  "team": null,
  "pos": "DST",
  "bye": 11,
  "tier": 2,
  "posRank": 8,
  "adp": 176,
  "boardRank": 176,
  "aav": 1
 },
 {
  "id": "Patriots",
  "name": "Patriots",
  "team": null,
  "pos": "DST",
  "bye": 11,
  "tier": 3,
  "posRank": 9,
  "adp": 177,
  "boardRank": 177,
  "aav": 1
 },
 {
  "id": "Lions",
  "name": "Lions",
  "team": null,
  "pos": "DST",
  "bye": 6,
  "tier": 3,
  "posRank": 10,
  "adp": 178,
  "boardRank": 178,
  "aav": 1
 },
 {
  "id": "Chiefs",
  "name": "Chiefs",
  "team": null,
  "pos": "DST",
  "bye": 5,
  "tier": 3,
  "posRank": 11,
  "adp": 179,
  "boardRank": 179,
  "aav": 0
 },
 {
  "id": "Chargers",
  "name": "Chargers",
  "team": null,
  "pos": "DST",
  "bye": 7,
  "tier": 3,
  "posRank": 12,
  "adp": 180,
  "boardRank": 180,
  "aav": 0
 },
 {
  "id": "Brandon Aubrey",
  "name": "Brandon Aubrey",
  "team": "DAL",
  "pos": "K",
  "bye": 14,
  "tier": 1,
  "posRank": 1,
  "adp": 181,
  "boardRank": 181,
  "aav": 1
 },
 {
  "id": "Cameron Dicker",
  "name": "Cameron Dicker",
  "team": "LAC",
  "pos": "K",
  "bye": 7,
  "tier": 1,
  "posRank": 2,
  "adp": 182,
  "boardRank": 182,
  "aav": 1
 },
 {
  "id": "Jason Myers",
  "name": "Jason Myers",
  "team": "SEA",
  "pos": "K",
  "bye": 11,
  "tier": 1,
  "posRank": 3,
  "adp": 183,
  "boardRank": 183,
  "aav": 1
 },
 {
  "id": "Harrison Mevis",
  "name": "Harrison Mevis",
  "team": "LAR",
  "pos": "K",
  "bye": 11,
  "tier": 2,
  "posRank": 4,
  "adp": 184,
  "boardRank": 184,
  "aav": 1
 },
 {
  "id": "Ka'imi Fairbairn",
  "name": "Ka'imi Fairbairn",
  "team": "HOU",
  "pos": "K",
  "bye": 8,
  "tier": 2,
  "posRank": 5,
  "adp": 185,
  "boardRank": 185,
  "aav": 1
 },
 {
  "id": "Eddy Pineiro",
  "name": "Eddy Pineiro",
  "team": "SF",
  "pos": "K",
  "bye": 8,
  "tier": 2,
  "posRank": 6,
  "adp": 186,
  "boardRank": 186,
  "aav": 1
 },
 {
  "id": "Harrison Butker",
  "name": "Harrison Butker",
  "team": "KC",
  "pos": "K",
  "bye": 5,
  "tier": 2,
  "posRank": 7,
  "adp": 187,
  "boardRank": 187,
  "aav": 1
 },
 {
  "id": "Cam Little",
  "name": "Cam Little",
  "team": "JAC",
  "pos": "K",
  "bye": 7,
  "tier": 2,
  "posRank": 8,
  "adp": 188,
  "boardRank": 188,
  "aav": 1
 },
 {
  "id": "Jake Bates",
  "name": "Jake Bates",
  "team": "DET",
  "pos": "K",
  "bye": 6,
  "tier": 3,
  "posRank": 9,
  "adp": 189,
  "boardRank": 189,
  "aav": 1
 },
 {
  "id": "Tyler Loop",
  "name": "Tyler Loop",
  "team": "BAL",
  "pos": "K",
  "bye": 13,
  "tier": 3,
  "posRank": 10,
  "adp": 190,
  "boardRank": 190,
  "aav": 1
 },
 {
  "id": "Cairo Santos",
  "name": "Cairo Santos",
  "team": "CHI",
  "pos": "K",
  "bye": 10,
  "tier": 3,
  "posRank": 11,
  "adp": 191,
  "boardRank": 191,
  "aav": 0
 },
 {
  "id": "Will Reichard",
  "name": "Will Reichard",
  "team": "MIN",
  "pos": "K",
  "bye": 6,
  "tier": 3,
  "posRank": 12,
  "adp": 192,
  "boardRank": 192,
  "aav": 0
 },
 {
  "id": "Justice Hill",
  "name": "Justice Hill",
  "team": "BAL",
  "pos": "RB",
  "bye": 13,
  "tier": 7,
  "posRank": 57,
  "adp": 193,
  "boardRank": 193,
  "aav": 0
 },
 {
  "id": "Brenton Strange",
  "name": "Brenton Strange",
  "team": "JAC",
  "pos": "TE",
  "bye": 7,
  "tier": 5,
  "posRank": 21,
  "adp": 194,
  "boardRank": 194,
  "aav": 0
 },
 {
  "id": "Jordan James",
  "name": "Jordan James",
  "team": "SF",
  "pos": "RB",
  "bye": 8,
  "tier": 7,
  "posRank": 58,
  "adp": 195,
  "boardRank": 195,
  "aav": 0
 },
 {
  "id": "Kaelon Black",
  "name": "Kaelon Black",
  "team": "SF",
  "pos": "RB",
  "bye": 8,
  "tier": 7,
  "posRank": 59,
  "adp": 196,
  "boardRank": 196,
  "aav": 0
 },
 {
  "id": "Chris Bell",
  "name": "Chris Bell",
  "team": "MIA",
  "pos": "WR",
  "bye": 6,
  "tier": 8,
  "posRank": 72,
  "adp": 197,
  "boardRank": 197,
  "aav": 0
 },
 {
  "id": "Jordan Love",
  "name": "Jordan Love",
  "team": "GB",
  "pos": "QB",
  "bye": 11,
  "tier": 5,
  "posRank": 22,
  "adp": 198,
  "boardRank": 198,
  "aav": 0
 },
 {
  "id": "Cam Ward",
  "name": "Cam Ward",
  "team": "TEN",
  "pos": "QB",
  "bye": 9,
  "tier": 6,
  "posRank": 23,
  "adp": 199,
  "boardRank": 199,
  "aav": 0
 },
 {
  "id": "C.J. Stroud",
  "name": "C.J. Stroud",
  "team": "HOU",
  "pos": "QB",
  "bye": 8,
  "tier": 6,
  "posRank": 24,
  "adp": 200,
  "boardRank": 200,
  "aav": 0
 },
 {
  "id": "Jack Bech",
  "name": "Jack Bech",
  "team": "LV",
  "pos": "WR",
  "bye": 13,
  "tier": 8,
  "posRank": 73,
  "adp": 201,
  "boardRank": 201,
  "aav": 0
 },
 {
  "id": "Deebo Samuel Sr.",
  "name": "Deebo Samuel Sr.",
  "team": "FA",
  "pos": "WR",
  "bye": null,
  "tier": 8,
  "posRank": 74,
  "adp": 202,
  "boardRank": 202,
  "aav": 0
 },
 {
  "id": "Stefon Diggs",
  "name": "Stefon Diggs",
  "team": "FA",
  "pos": "WR",
  "bye": null,
  "tier": 8,
  "posRank": 75,
  "adp": 203,
  "boardRank": 203,
  "aav": 0
 },
 {
  "id": "Tre Harris",
  "name": "Tre Harris",
  "team": "LAC",
  "pos": "WR",
  "bye": 7,
  "tier": 8,
  "posRank": 76,
  "adp": 204,
  "boardRank": 204,
  "aav": 0
 },
 {
  "id": "Isaac TeSlaa",
  "name": "Isaac TeSlaa",
  "team": "DET",
  "pos": "WR",
  "bye": 6,
  "tier": 8,
  "posRank": 77,
  "adp": 205,
  "boardRank": 205,
  "aav": 0
 },
 {
  "id": "Pat Freiermuth",
  "name": "Pat Freiermuth",
  "team": "PIT",
  "pos": "TE",
  "bye": 9,
  "tier": 5,
  "posRank": 22,
  "adp": 206,
  "boardRank": 206,
  "aav": 0
 },
 {
  "id": "Dalton Schultz",
  "name": "Dalton Schultz",
  "team": "HOU",
  "pos": "TE",
  "bye": 8,
  "tier": 5,
  "posRank": 23,
  "adp": 207,
  "boardRank": 207,
  "aav": 0
 },
 {
  "id": "Ryan Flournoy",
  "name": "Ryan Flournoy",
  "team": "DAL",
  "pos": "WR",
  "bye": 14,
  "tier": 8,
  "posRank": 78,
  "adp": 208,
  "boardRank": 208,
  "aav": 0
 },
 {
  "id": "Brandon Aiyuk",
  "name": "Brandon Aiyuk",
  "team": "SF",
  "pos": "WR",
  "bye": 8,
  "tier": 8,
  "posRank": 79,
  "adp": 209,
  "boardRank": 209,
  "aav": 0
 },
 {
  "id": "Cooper Kupp",
  "name": "Cooper Kupp",
  "team": "SEA",
  "pos": "WR",
  "bye": 11,
  "tier": 8,
  "posRank": 80,
  "adp": 210,
  "boardRank": 210,
  "aav": 0
 },
 {
  "id": "Tank Dell",
  "name": "Tank Dell",
  "team": "HOU",
  "pos": "WR",
  "bye": 8,
  "tier": 8,
  "posRank": 81,
  "adp": 211,
  "boardRank": 211,
  "aav": 0
 },
 {
  "id": "Kaytron Allen",
  "name": "Kaytron Allen",
  "team": "WAS",
  "pos": "RB",
  "bye": 7,
  "tier": 7,
  "posRank": 60,
  "adp": 212,
  "boardRank": 212,
  "aav": 0
 },
 {
  "id": "Nicholas Singleton",
  "name": "Nicholas Singleton",
  "team": "TEN",
  "pos": "RB",
  "bye": 9,
  "tier": 7,
  "posRank": 61,
  "adp": 213,
  "boardRank": 213,
  "aav": 0
 },
 {
  "id": "Demond Claiborne",
  "name": "Demond Claiborne",
  "team": "MIN",
  "pos": "RB",
  "bye": 6,
  "tier": 7,
  "posRank": 62,
  "adp": 214,
  "boardRank": 214,
  "aav": 0
 },
 {
  "id": "Gunnar Helm",
  "name": "Gunnar Helm",
  "team": "TEN",
  "pos": "TE",
  "bye": 9,
  "tier": 5,
  "posRank": 24,
  "adp": 215,
  "boardRank": 215,
  "aav": 0
 },
 {
  "id": "Oronde Gadsden",
  "name": "Oronde Gadsden",
  "team": "LAC",
  "pos": "TE",
  "bye": 7,
  "tier": 6,
  "posRank": 25,
  "adp": 216,
  "boardRank": 216,
  "aav": 0
 },
 {
  "id": "Chig Okonkwo",
  "name": "Chig Okonkwo",
  "team": "WAS",
  "pos": "TE",
  "bye": 7,
  "tier": 6,
  "posRank": 26,
  "adp": 217,
  "boardRank": 217,
  "aav": 0
 },
 {
  "id": "Sam Darnold",
  "name": "Sam Darnold",
  "team": "SEA",
  "pos": "QB",
  "bye": 11,
  "tier": 6,
  "posRank": 25,
  "adp": 218,
  "boardRank": 218,
  "aav": 0
 },
 {
  "id": "Bryce Young",
  "name": "Bryce Young",
  "team": "CAR",
  "pos": "QB",
  "bye": 5,
  "tier": 6,
  "posRank": 26,
  "adp": 219,
  "boardRank": 219,
  "aav": 0
 },
 {
  "id": "Fernando Mendoza",
  "name": "Fernando Mendoza",
  "team": "LV",
  "pos": "QB",
  "bye": 13,
  "tier": 6,
  "posRank": 27,
  "adp": 220,
  "boardRank": 220,
  "aav": 0
 },
 {
  "id": "Jonah Coleman",
  "name": "Jonah Coleman",
  "team": "DEN",
  "pos": "RB",
  "bye": 10,
  "tier": 7,
  "posRank": 63,
  "adp": 221,
  "boardRank": 221,
  "aav": 0
 },
 {
  "id": "Seth McGowan",
  "name": "Seth McGowan",
  "team": "IND",
  "pos": "RB",
  "bye": 13,
  "tier": 7,
  "posRank": 64,
  "adp": 222,
  "boardRank": 222,
  "aav": 0
 },
 {
  "id": "Emmett Johnson",
  "name": "Emmett Johnson",
  "team": "KC",
  "pos": "RB",
  "bye": 5,
  "tier": 7,
  "posRank": 65,
  "adp": 223,
  "boardRank": 223,
  "aav": 0
 },
 {
  "id": "Zachariah Branch",
  "name": "Zachariah Branch",
  "team": "ATL",
  "pos": "WR",
  "bye": 11,
  "tier": 8,
  "posRank": 82,
  "adp": 224,
  "boardRank": 224,
  "aav": 0
 },
 {
  "id": "Dylan Sampson",
  "name": "Dylan Sampson",
  "team": "CLE",
  "pos": "RB",
  "bye": 11,
  "tier": 7,
  "posRank": 66,
  "adp": 225,
  "boardRank": 225,
  "aav": 0
 },
 {
  "id": "Samaje Perine",
  "name": "Samaje Perine",
  "team": "CIN",
  "pos": "RB",
  "bye": 6,
  "tier": 7,
  "posRank": 67,
  "adp": 226,
  "boardRank": 226,
  "aav": 0
 },
 {
  "id": "Caleb Douglas",
  "name": "Caleb Douglas",
  "team": "MIA",
  "pos": "WR",
  "bye": 6,
  "tier": 8,
  "posRank": 83,
  "adp": 227,
  "boardRank": 227,
  "aav": 0
 },
 {
  "id": "Jalen Tolbert",
  "name": "Jalen Tolbert",
  "team": "MIA",
  "pos": "WR",
  "bye": 6,
  "tier": 8,
  "posRank": 84,
  "adp": 228,
  "boardRank": 228,
  "aav": 0
 },
 {
  "id": "Malik Washington",
  "name": "Malik Washington",
  "team": "MIA",
  "pos": "WR",
  "bye": 6,
  "tier": 8,
  "posRank": 85,
  "adp": 229,
  "boardRank": 229,
  "aav": 0
 },
 {
  "id": "Christian Kirk",
  "name": "Christian Kirk",
  "team": "SF",
  "pos": "WR",
  "bye": 8,
  "tier": 8,
  "posRank": 86,
  "adp": 230,
  "boardRank": 230,
  "aav": 0
 },
 {
  "id": "Savion Williams",
  "name": "Savion Williams",
  "team": "GB",
  "pos": "WR",
  "bye": 11,
  "tier": 8,
  "posRank": 87,
  "adp": 231,
  "boardRank": 231,
  "aav": 0
 },
 {
  "id": "Chris Brazzell II",
  "name": "Chris Brazzell II",
  "team": "CAR",
  "pos": "WR",
  "bye": 5,
  "tier": 8,
  "posRank": 88,
  "adp": 232,
  "boardRank": 232,
  "aav": 0
 },
 {
  "id": "Tyreek Hill",
  "name": "Tyreek Hill",
  "team": "FA",
  "pos": "WR",
  "bye": null,
  "tier": 8,
  "posRank": 89,
  "adp": 233,
  "boardRank": 233,
  "aav": 0
 },
 {
  "id": "De'Zhaun Stribling",
  "name": "De'Zhaun Stribling",
  "team": "SF",
  "pos": "WR",
  "bye": 8,
  "tier": 8,
  "posRank": 90,
  "adp": 234,
  "boardRank": 234,
  "aav": 0
 },
 {
  "id": "Buccaneers",
  "name": "Buccaneers",
  "team": null,
  "pos": "DST",
  "bye": 10,
  "tier": 3,
  "posRank": 13,
  "adp": 235,
  "boardRank": 235,
  "aav": 0
 },
 {
  "id": "Packers",
  "name": "Packers",
  "team": null,
  "pos": "DST",
  "bye": 11,
  "tier": 3,
  "posRank": 14,
  "adp": 236,
  "boardRank": 236,
  "aav": 0
 },
 {
  "id": "Chris Boswell",
  "name": "Chris Boswell",
  "team": "PIT",
  "pos": "K",
  "bye": 9,
  "tier": 3,
  "posRank": 13,
  "adp": 237,
  "boardRank": 237,
  "aav": 0
 },
 {
  "id": "Chase McLaughlin",
  "name": "Chase McLaughlin",
  "team": "TB",
  "pos": "K",
  "bye": 10,
  "tier": 3,
  "posRank": 14,
  "adp": 238,
  "boardRank": 238,
  "aav": 0
 },
 {
  "id": "LeQuint Allen",
  "name": "LeQuint Allen",
  "team": "JAC",
  "pos": "RB",
  "bye": 7,
  "tier": 7,
  "posRank": 68,
  "adp": 239,
  "boardRank": 239,
  "aav": 0
 },
 {
  "id": "Jaylen Wright",
  "name": "Jaylen Wright",
  "team": "MIA",
  "pos": "RB",
  "bye": 6,
  "tier": 8,
  "posRank": 69,
  "adp": 240,
  "boardRank": 240,
  "aav": 0
 },
 {
  "id": "Ollie Gordon II",
  "name": "Ollie Gordon II",
  "team": "MIA",
  "pos": "RB",
  "bye": 6,
  "tier": 8,
  "posRank": 70,
  "adp": 241,
  "boardRank": 241,
  "aav": 0
 },
 {
  "id": "Kimani Vidal",
  "name": "Kimani Vidal",
  "team": "LAC",
  "pos": "RB",
  "bye": 7,
  "tier": 8,
  "posRank": 71,
  "adp": 242,
  "boardRank": 242,
  "aav": 0
 },
 {
  "id": "Adam Randall",
  "name": "Adam Randall",
  "team": "BAL",
  "pos": "RB",
  "bye": 13,
  "tier": 8,
  "posRank": 72,
  "adp": 243,
  "boardRank": 243,
  "aav": 0
 },
 {
  "id": "MarShawn Lloyd",
  "name": "MarShawn Lloyd",
  "team": "GB",
  "pos": "RB",
  "bye": 11,
  "tier": 8,
  "posRank": 73,
  "adp": 244,
  "boardRank": 244,
  "aav": 0
 },
 {
  "id": "Emari Demercado",
  "name": "Emari Demercado",
  "team": "KC",
  "pos": "RB",
  "bye": 5,
  "tier": 8,
  "posRank": 74,
  "adp": 245,
  "boardRank": 245,
  "aav": 0
 },
 {
  "id": "Jaydon Blue",
  "name": "Jaydon Blue",
  "team": "DAL",
  "pos": "RB",
  "bye": 14,
  "tier": 8,
  "posRank": 75,
  "adp": 246,
  "boardRank": 246,
  "aav": 0
 },
 {
  "id": "Trey Benson",
  "name": "Trey Benson",
  "team": "ARI",
  "pos": "RB",
  "bye": 14,
  "tier": 8,
  "posRank": 76,
  "adp": 247,
  "boardRank": 247,
  "aav": 0
 },
 {
  "id": "Kaleb Johnson",
  "name": "Kaleb Johnson",
  "team": "PIT",
  "pos": "RB",
  "bye": 9,
  "tier": 8,
  "posRank": 77,
  "adp": 248,
  "boardRank": 248,
  "aav": 0
 },
 {
  "id": "Ty Johnson",
  "name": "Ty Johnson",
  "team": "BUF",
  "pos": "RB",
  "bye": 7,
  "tier": 8,
  "posRank": 78,
  "adp": 249,
  "boardRank": 249,
  "aav": 0
 },
 {
  "id": "Kyle Juszczyk",
  "name": "Kyle Juszczyk",
  "team": "SF",
  "pos": "RB",
  "bye": 8,
  "tier": 8,
  "posRank": 79,
  "adp": 250,
  "boardRank": 250,
  "aav": 0
 },
 {
  "id": "Chris Brooks",
  "name": "Chris Brooks",
  "team": "GB",
  "pos": "RB",
  "bye": 11,
  "tier": 8,
  "posRank": 80,
  "adp": 251,
  "boardRank": 251,
  "aav": 0
 },
 {
  "id": "Jaguars",
  "name": "Jaguars",
  "team": null,
  "pos": "DST",
  "bye": 7,
  "tier": 3,
  "posRank": 15,
  "adp": 254,
  "boardRank": 252,
  "aav": 0
 },
 {
  "id": "Evan McPherson",
  "name": "Evan McPherson",
  "team": "CIN",
  "pos": "K",
  "bye": 6,
  "tier": 3,
  "posRank": 15,
  "adp": 256,
  "boardRank": 253,
  "aav": 0
 },
 {
  "id": "AJ Barner",
  "name": "AJ Barner",
  "team": "SEA",
  "pos": "TE",
  "bye": 11,
  "tier": 6,
  "posRank": 27,
  "adp": 258,
  "boardRank": 254,
  "aav": 0
 },
 {
  "id": "Greg Dulcich",
  "name": "Greg Dulcich",
  "team": "MIA",
  "pos": "TE",
  "bye": 6,
  "tier": 6,
  "posRank": 28,
  "adp": 259,
  "boardRank": 255,
  "aav": 0
 },
 {
  "id": "Cade Otton",
  "name": "Cade Otton",
  "team": "TB",
  "pos": "TE",
  "bye": 10,
  "tier": 6,
  "posRank": 29,
  "adp": 260,
  "boardRank": 256,
  "aav": 0
 },
 {
  "id": "George Holani",
  "name": "George Holani",
  "team": "SEA",
  "pos": "RB",
  "bye": 11,
  "tier": 8,
  "posRank": 81,
  "adp": 265,
  "boardRank": 257,
  "aav": 0
 },
 {
  "id": "Isaiah Davis",
  "name": "Isaiah Davis",
  "team": "NYJ",
  "pos": "RB",
  "bye": 13,
  "tier": 8,
  "posRank": 82,
  "adp": 266,
  "boardRank": 258,
  "aav": 0
 },
 {
  "id": "Geno Smith",
  "name": "Geno Smith",
  "team": "NYJ",
  "pos": "QB",
  "bye": 13,
  "tier": 6,
  "posRank": 28,
  "adp": 267,
  "boardRank": 259,
  "aav": 0
 },
 {
  "id": "Aaron Rodgers",
  "name": "Aaron Rodgers",
  "team": "PIT",
  "pos": "QB",
  "bye": 9,
  "tier": 6,
  "posRank": 29,
  "adp": 268,
  "boardRank": 260,
  "aav": 0
 },
 {
  "id": "Deshaun Watson",
  "name": "Deshaun Watson",
  "team": "CLE",
  "pos": "QB",
  "bye": 11,
  "tier": 6,
  "posRank": 30,
  "adp": 269,
  "boardRank": 261,
  "aav": 0
 },
 {
  "id": "Jacoby Brissett",
  "name": "Jacoby Brissett",
  "team": "ARI",
  "pos": "QB",
  "bye": 14,
  "tier": 7,
  "posRank": 31,
  "adp": 270,
  "boardRank": 262,
  "aav": 0
 },
 {
  "id": "DJ Giddens",
  "name": "DJ Giddens",
  "team": "IND",
  "pos": "RB",
  "bye": 13,
  "tier": 8,
  "posRank": 83,
  "adp": 276,
  "boardRank": 263,
  "aav": 0
 },
 {
  "id": "Malik Davis",
  "name": "Malik Davis",
  "team": "DAL",
  "pos": "RB",
  "bye": 14,
  "tier": 8,
  "posRank": 84,
  "adp": 277,
  "boardRank": 264,
  "aav": 0
 },
 {
  "id": "Sean Tucker",
  "name": "Sean Tucker",
  "team": "TB",
  "pos": "RB",
  "bye": 10,
  "tier": 8,
  "posRank": 85,
  "adp": 278,
  "boardRank": 265,
  "aav": 0
 },
 {
  "id": "Mike Gesicki",
  "name": "Mike Gesicki",
  "team": "CIN",
  "pos": "TE",
  "bye": 6,
  "tier": 6,
  "posRank": 30,
  "adp": 289,
  "boardRank": 266,
  "aav": 0
 },
 {
  "id": "Evan Engram",
  "name": "Evan Engram",
  "team": "DEN",
  "pos": "TE",
  "bye": 10,
  "tier": 6,
  "posRank": 31,
  "adp": 290,
  "boardRank": 267,
  "aav": 0
 },
 {
  "id": "David Njoku",
  "name": "David Njoku",
  "team": "LAC",
  "pos": "TE",
  "bye": 7,
  "tier": 6,
  "posRank": 32,
  "adp": 291,
  "boardRank": 268,
  "aav": 0
 },
 {
  "id": "Michael Mayer",
  "name": "Michael Mayer",
  "team": "LV",
  "pos": "TE",
  "bye": 13,
  "tier": 6,
  "posRank": 33,
  "adp": 292,
  "boardRank": 269,
  "aav": 0
 },
 {
  "id": "Jake Tonges",
  "name": "Jake Tonges",
  "team": "SF",
  "pos": "TE",
  "bye": 8,
  "tier": 6,
  "posRank": 34,
  "adp": 293,
  "boardRank": 270,
  "aav": 0
 },
 {
  "id": "Tua Tagovailoa",
  "name": "Tua Tagovailoa",
  "team": "ATL",
  "pos": "QB",
  "bye": 11,
  "tier": 7,
  "posRank": 32,
  "adp": 296,
  "boardRank": 271,
  "aav": 0
 },
 {
  "id": "Shedeur Sanders",
  "name": "Shedeur Sanders",
  "team": "CLE",
  "pos": "QB",
  "bye": 11,
  "tier": 7,
  "posRank": 33,
  "adp": 301,
  "boardRank": 272,
  "aav": 0
 },
 {
  "id": "Kirk Cousins",
  "name": "Kirk Cousins",
  "team": "LV",
  "pos": "QB",
  "bye": 13,
  "tier": 7,
  "posRank": 34,
  "adp": 302,
  "boardRank": 273,
  "aav": 0
 },
 {
  "id": "Michael Penix Jr.",
  "name": "Michael Penix Jr.",
  "team": "ATL",
  "pos": "QB",
  "bye": 11,
  "tier": 7,
  "posRank": 35,
  "adp": 310,
  "boardRank": 274,
  "aav": 0
 },
 {
  "id": "Ja'Tavion Sanders",
  "name": "Ja'Tavion Sanders",
  "team": "CAR",
  "pos": "TE",
  "bye": 5,
  "tier": 6,
  "posRank": 35,
  "adp": 311,
  "boardRank": 275,
  "aav": 0
 },
 {
  "id": "J.J. McCarthy",
  "name": "J.J. McCarthy",
  "team": "MIN",
  "pos": "QB",
  "bye": 6,
  "tier": 7,
  "posRank": 36,
  "adp": 315,
  "boardRank": 276,
  "aav": 0
 },
 {
  "id": "Carson Beck",
  "name": "Carson Beck",
  "team": "ARI",
  "pos": "QB",
  "bye": 14,
  "tier": 7,
  "posRank": 37,
  "adp": 316,
  "boardRank": 277,
  "aav": 0
 },
 {
  "id": "Justin Fields",
  "name": "Justin Fields",
  "team": "KC",
  "pos": "QB",
  "bye": 5,
  "tier": 7,
  "posRank": 38,
  "adp": 317,
  "boardRank": 278,
  "aav": 0
 },
 {
  "id": "Joe Flacco",
  "name": "Joe Flacco",
  "team": "CIN",
  "pos": "QB",
  "bye": 6,
  "tier": 7,
  "posRank": 39,
  "adp": 318,
  "boardRank": 279,
  "aav": 0
 },
 {
  "id": "Mac Jones",
  "name": "Mac Jones",
  "team": "SF",
  "pos": "QB",
  "bye": 8,
  "tier": 7,
  "posRank": 40,
  "adp": 319,
  "boardRank": 280,
  "aav": 0
 }
];
